# Generated by Django 6.1.1 on 2026-09-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_program_section_year_level_subject_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='effective_from',
            field=models.DateField(blank=True, help_text='First date this schedule is active (leave blank = no start restriction)', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Last date this schedule is active (leave blank = no end restriction)', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='college',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
