# Generated by Django 6.1.1 on 2026-09-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schedule_effective_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day_2',
            field=models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], help_text='Second meeting day (e.g. Thu for a Tue–Thu pattern). Leave blank for single-day classes.', max_length=3, null=True, verbose_name='Day 2'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=3, verbose_name='Day 1'),
        ),
    ]
