# Generated by Django 6.1.1 on 2026-09-22 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schedule_add_day2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year_level', models.PositiveSmallIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1)),
                ('description', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_sections', to='core.program')),
            ],
            options={
                'verbose_name': 'Program Section',
                'verbose_name_plural': 'Program Sections',
                'ordering': ['program__code', 'year_level', 'name'],
                'unique_together': {('program', 'name')},
            },
        ),
        migrations.AddField(
            model_name='section',
            name='program_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='core.programsection'),
        ),
    ]
