# Generated by Django 6.1.1 on 2026-09-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_programsection_section_program_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('schedule', 'date')},
        ),
    ]
