# Generated by Django 6.1.1 on 2026-09-23 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_user_role_idx_customuser_user_name_idx_and_more'),
        ('core', '0006_alter_attendancesession_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_started', to='accounts.teacher'),
        ),
    ]
