# Generated by Django 6.1.1 on 2026-09-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_user_role_idx_customuser_user_name_idx_and_more'),
        ('core', '0007_alter_attendancesession_started_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='The specific academic course subject this schedule meeting belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.subject'),
        ),
        migrations.AddField(
            model_name='studentsection',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Leave blank for regular block section; select subject for irregular student.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='core.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsection',
            unique_together={('student', 'section', 'subject')},
        ),
    ]
