# Generated by Django 6.1.1 on 2026-09-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_studentsection_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programsection',
            options={'ordering': ['program__code', 'course', 'year_level', 'name'], 'verbose_name': 'Program Section', 'verbose_name_plural': 'Program Sections'},
        ),
        migrations.AddField(
            model_name='programsection',
            name='course',
            field=models.CharField(blank=True, default='', help_text='Course/Degree program abbreviation (e.g., BSIT, BSCS, BSEMC, BSA, BSCrim)', max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
