# Generated by Django 6.1.1 on 2026-09-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='user_role_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['last_name', 'first_name'], name='user_name_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course', 'year_level'], name='student_crs_yr_idx'),
        ),
    ]
