# Generated by Django 6.1.1 on 2026-09-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_user_role_idx_customuser_user_name_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_place',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='citizenship',
            field=models.CharField(blank=True, default='Filipino', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='civil_status',
            field=models.CharField(blank=True, default='Single', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='current_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='current_municipality',
            field=models.CharField(blank=True, default='Butuan City', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='current_province',
            field=models.CharField(blank=True, default='Agusan del Norte', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='current_region',
            field=models.CharField(blank=True, default='REGION XIII (Caraga)', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='height',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='languages_spoken',
            field=models.CharField(blank=True, default='English, Filipino, Cebuano', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_municipality',
            field=models.CharField(blank=True, default='Butuan City', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_province',
            field=models.CharField(blank=True, default='Agusan del Norte', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_region',
            field=models.CharField(blank=True, default='REGION XIII (Caraga)', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, default='Roman Catholic', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
